- job_name: 'msa-store-services'
  kubernetes_sd_configs:
  - role: endpoints
 
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name]
    action: keep
    regex: (.+-service)
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    action: keep
    regex: prometheus