apiVersion: v1
kind: BuildConfig
metadata:
  name: inventory-service-pipeline
  labels:
    name: inventory-service-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "inventory-service", "namespace": "msa-store-dev", "kind": "DeploymentConfig"}, {"name": "inventory-service", "namespace": "msa-store-prod", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node ('nodejs') {
          stage ('Build') {
            openshiftBuild(namespace: 'msa-store-dev', bldCfg: 'inventory-service', showBuildLogs: 'true')
          }
          stage ('Deploy Dev') {
            openshiftDeploy(namespace: 'msa-store-dev', depCfg:  'inventory-service')
          }
          stage ('Acceptance Tests') {
            sleep 13
          }
          stage ('Promote to Prod') {
            openshiftTag(namespace: 'msa-store-dev', sourceStream:'inventory-service', sourceTag:'latest', destinationStream:'inventory-service', destinationTag:'promoteToProd')
          }
          stage ('Deploy Prod') {
            openshiftDeploy(namespace: 'msa-store-prod', depCfg:  'inventory-service')
          }
        }
  output:
  resources:
  postCommit:
