spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
#              memory: 256Mi
            limits:
              cpu: "1.0"
#              memory: 256Mi
          env:
          - name: ACTIVEMQ_SERVICE_NAME
            value: broker-amq-tcp
          - name: JAEGER_SERVER_HOSTNAME
            value: jaeger-agent.cockpit.svc.cluster.local
          - name: JAVA_OPTIONS
            value: -javaagent:agent/jmx_prometheus_javaagent-0.10.jar=9779:agent/config.yml
